spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: dummy_username
    password: dummy_password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect